package com.zyyglxt.dataobject;

import java.util.Date;

public class ApplicationDO extends ApplicationDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_DESCRIPTION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Integer appType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_IMAGEURL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appImageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_APPURL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appAppurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_PORT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_REMOTE_LOGIN
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appRemoteLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_PASSWORD_ERROR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Integer appPasswordError;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_AUTO_EXIT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Integer appAutoExit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APP_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_NAME
     *
     * @return the value of application.APP_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_NAME
     *
     * @param appName the value for application.APP_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_DESCRIPTION
     *
     * @return the value of application.APP_DESCRIPTION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppDescription() {
        return appDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_DESCRIPTION
     *
     * @param appDescription the value for application.APP_DESCRIPTION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppDescription(String appDescription) {
        this.appDescription = appDescription == null ? null : appDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_TYPE
     *
     * @return the value of application.APP_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Integer getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_TYPE
     *
     * @param appType the value for application.APP_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppType(Integer appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_IMAGEURL
     *
     * @return the value of application.APP_IMAGEURL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppImageurl() {
        return appImageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_IMAGEURL
     *
     * @param appImageurl the value for application.APP_IMAGEURL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppImageurl(String appImageurl) {
        this.appImageurl = appImageurl == null ? null : appImageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_APPURL
     *
     * @return the value of application.APP_APPURL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppAppurl() {
        return appAppurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_APPURL
     *
     * @param appAppurl the value for application.APP_APPURL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppAppurl(String appAppurl) {
        this.appAppurl = appAppurl == null ? null : appAppurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_PORT
     *
     * @return the value of application.APP_PORT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppPort() {
        return appPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_PORT
     *
     * @param appPort the value for application.APP_PORT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppPort(String appPort) {
        this.appPort = appPort == null ? null : appPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_REMOTE_LOGIN
     *
     * @return the value of application.APP_REMOTE_LOGIN
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppRemoteLogin() {
        return appRemoteLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_REMOTE_LOGIN
     *
     * @param appRemoteLogin the value for application.APP_REMOTE_LOGIN
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppRemoteLogin(String appRemoteLogin) {
        this.appRemoteLogin = appRemoteLogin == null ? null : appRemoteLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_PASSWORD_ERROR
     *
     * @return the value of application.APP_PASSWORD_ERROR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Integer getAppPasswordError() {
        return appPasswordError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_PASSWORD_ERROR
     *
     * @param appPasswordError the value for application.APP_PASSWORD_ERROR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppPasswordError(Integer appPasswordError) {
        this.appPasswordError = appPasswordError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_AUTO_EXIT
     *
     * @return the value of application.APP_AUTO_EXIT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Integer getAppAutoExit() {
        return appAutoExit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_AUTO_EXIT
     *
     * @param appAutoExit the value for application.APP_AUTO_EXIT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppAutoExit(Integer appAutoExit) {
        this.appAutoExit = appAutoExit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APP_STATUS
     *
     * @return the value of application.APP_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APP_STATUS
     *
     * @param appStatus the value for application.APP_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus == null ? null : appStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.CREATER
     *
     * @return the value of application.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.CREATER
     *
     * @param creater the value for application.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.itemCreateAt
     *
     * @return the value of application.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.itemCreateAt
     *
     * @param itemcreateat the value for application.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.UPDATER
     *
     * @return the value of application.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.UPDATER
     *
     * @param updater the value for application.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.itemUpdateAt
     *
     * @return the value of application.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.itemUpdateAt
     *
     * @param itemupdateat the value for application.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}