package com.zyyglxt.dataobject;

public class ChineseMedicineDOWithBLOBs extends ChineseMedicineDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_medicine.EXPERT_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String expertIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_medicine.MEDICINE_RECORDS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String medicineRecords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_medicine.EXPERT_INTRODUCE
     *
     * @return the value of tb_culpro_chinese_medicine.EXPERT_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getExpertIntroduce() {
        return expertIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_medicine.EXPERT_INTRODUCE
     *
     * @param expertIntroduce the value for tb_culpro_chinese_medicine.EXPERT_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setExpertIntroduce(String expertIntroduce) {
        this.expertIntroduce = expertIntroduce == null ? null : expertIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_medicine.MEDICINE_RECORDS
     *
     * @return the value of tb_culpro_chinese_medicine.MEDICINE_RECORDS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getMedicineRecords() {
        return medicineRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_medicine.MEDICINE_RECORDS
     *
     * @param medicineRecords the value for tb_culpro_chinese_medicine.MEDICINE_RECORDS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setMedicineRecords(String medicineRecords) {
        this.medicineRecords = medicineRecords == null ? null : medicineRecords.trim();
    }
}