package com.zyyglxt.dataobject;

public class ChineseCulturalDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.itemID
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.itemCode
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String itemcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.itemID
     *
     * @return the value of tb_culpro_chinese_cultural.itemID
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.itemID
     *
     * @param itemid the value for tb_culpro_chinese_cultural.itemID
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.itemCode
     *
     * @return the value of tb_culpro_chinese_cultural.itemCode
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.itemCode
     *
     * @param itemcode the value for tb_culpro_chinese_cultural.itemCode
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode == null ? null : itemcode.trim();
    }
}