package com.zyyglxt.dataobject;

import lombok.ToString;

import java.util.Date;

@ToString
public class ChineseCulturalDO extends ChineseCulturalDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_NAME
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String chineseCulturalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_SOURCE
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String chineseCulturalSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_AUTHOR
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String chineseCulturalAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.VISIT_NUM
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private Integer visitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_TYPE
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String chineseCulturalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_STATUS
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String chineseCulturalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.CREATER
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.itemCreateAt
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.UPDATER
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.itemUpdateAt
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private Date itemupdateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_URL
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String chineseCulturalUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_CONTENT
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    private String chineseCulturalContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_NAME
     *
     * @return the value of tb_culpro_chinese_cultural.CHINESE_CULTURAL_NAME
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getChineseCulturalName() {
        return chineseCulturalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_NAME
     *
     * @param chineseCulturalName the value for tb_culpro_chinese_cultural.CHINESE_CULTURAL_NAME
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setChineseCulturalName(String chineseCulturalName) {
        this.chineseCulturalName = chineseCulturalName == null ? null : chineseCulturalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_SOURCE
     *
     * @return the value of tb_culpro_chinese_cultural.CHINESE_CULTURAL_SOURCE
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getChineseCulturalSource() {
        return chineseCulturalSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_SOURCE
     *
     * @param chineseCulturalSource the value for tb_culpro_chinese_cultural.CHINESE_CULTURAL_SOURCE
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setChineseCulturalSource(String chineseCulturalSource) {
        this.chineseCulturalSource = chineseCulturalSource == null ? null : chineseCulturalSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_AUTHOR
     *
     * @return the value of tb_culpro_chinese_cultural.CHINESE_CULTURAL_AUTHOR
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getChineseCulturalAuthor() {
        return chineseCulturalAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_AUTHOR
     *
     * @param chineseCulturalAuthor the value for tb_culpro_chinese_cultural.CHINESE_CULTURAL_AUTHOR
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setChineseCulturalAuthor(String chineseCulturalAuthor) {
        this.chineseCulturalAuthor = chineseCulturalAuthor == null ? null : chineseCulturalAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.VISIT_NUM
     *
     * @return the value of tb_culpro_chinese_cultural.VISIT_NUM
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public Integer getVisitNum() {
        return visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.VISIT_NUM
     *
     * @param visitNum the value for tb_culpro_chinese_cultural.VISIT_NUM
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setVisitNum(Integer visitNum) {
        this.visitNum = visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_TYPE
     *
     * @return the value of tb_culpro_chinese_cultural.CHINESE_CULTURAL_TYPE
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getChineseCulturalType() {
        return chineseCulturalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_TYPE
     *
     * @param chineseCulturalType the value for tb_culpro_chinese_cultural.CHINESE_CULTURAL_TYPE
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setChineseCulturalType(String chineseCulturalType) {
        this.chineseCulturalType = chineseCulturalType == null ? null : chineseCulturalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_STATUS
     *
     * @return the value of tb_culpro_chinese_cultural.CHINESE_CULTURAL_STATUS
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getChineseCulturalStatus() {
        return chineseCulturalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_STATUS
     *
     * @param chineseCulturalStatus the value for tb_culpro_chinese_cultural.CHINESE_CULTURAL_STATUS
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setChineseCulturalStatus(String chineseCulturalStatus) {
        this.chineseCulturalStatus = chineseCulturalStatus == null ? null : chineseCulturalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.CREATER
     *
     * @return the value of tb_culpro_chinese_cultural.CREATER
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.CREATER
     *
     * @param creater the value for tb_culpro_chinese_cultural.CREATER
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.itemCreateAt
     *
     * @return the value of tb_culpro_chinese_cultural.itemCreateAt
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.itemCreateAt
     *
     * @param itemcreateat the value for tb_culpro_chinese_cultural.itemCreateAt
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.UPDATER
     *
     * @return the value of tb_culpro_chinese_cultural.UPDATER
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.UPDATER
     *
     * @param updater the value for tb_culpro_chinese_cultural.UPDATER
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.itemUpdateAt
     *
     * @return the value of tb_culpro_chinese_cultural.itemUpdateAt
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.itemUpdateAt
     *
     * @param itemupdateat the value for tb_culpro_chinese_cultural.itemUpdateAt
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_URL
     *
     * @return the value of tb_culpro_chinese_cultural.CHINESE_CULTURAL_URL
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getChineseCulturalUrl() {
        return chineseCulturalUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_URL
     *
     * @param chineseCulturalUrl the value for tb_culpro_chinese_cultural.CHINESE_CULTURAL_URL
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setChineseCulturalUrl(String chineseCulturalUrl) {
        this.chineseCulturalUrl = chineseCulturalUrl == null ? null : chineseCulturalUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_CONTENT
     *
     * @return the value of tb_culpro_chinese_cultural.CHINESE_CULTURAL_CONTENT
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public String getChineseCulturalContent() {
        return chineseCulturalContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_chinese_cultural.CHINESE_CULTURAL_CONTENT
     *
     * @param chineseCulturalContent the value for tb_culpro_chinese_cultural.CHINESE_CULTURAL_CONTENT
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    public void setChineseCulturalContent(String chineseCulturalContent) {
        this.chineseCulturalContent = chineseCulturalContent == null ? null : chineseCulturalContent.trim();
    }
}