package com.zyyglxt.dataobject;

import java.util.Date;

public class DictDO extends DictDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.DICT_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.DICT_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.DICT_ISTREE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String dictIstree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.DICT_DESCRIPTION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String dictDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.DICT_NAME
     *
     * @return the value of dict.DICT_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.DICT_NAME
     *
     * @param dictName the value for dict.DICT_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.DICT_CODE
     *
     * @return the value of dict.DICT_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.DICT_CODE
     *
     * @param dictCode the value for dict.DICT_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.DICT_ISTREE
     *
     * @return the value of dict.DICT_ISTREE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getDictIstree() {
        return dictIstree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.DICT_ISTREE
     *
     * @param dictIstree the value for dict.DICT_ISTREE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setDictIstree(String dictIstree) {
        this.dictIstree = dictIstree == null ? null : dictIstree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.DICT_DESCRIPTION
     *
     * @return the value of dict.DICT_DESCRIPTION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getDictDescription() {
        return dictDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.DICT_DESCRIPTION
     *
     * @param dictDescription the value for dict.DICT_DESCRIPTION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setDictDescription(String dictDescription) {
        this.dictDescription = dictDescription == null ? null : dictDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.CREATER
     *
     * @return the value of dict.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.CREATER
     *
     * @param creater the value for dict.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.itemCreateAt
     *
     * @return the value of dict.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.itemCreateAt
     *
     * @param itemcreateat the value for dict.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.UPDATER
     *
     * @return the value of dict.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.UPDATER
     *
     * @param updater the value for dict.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.itemUpdateAt
     *
     * @return the value of dict.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.itemUpdateAt
     *
     * @param itemupdateat the value for dict.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}