package com.zyyglxt.dataobject;

public class DoctorDOWithBLOBs extends DoctorDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_doctor.DOCTOR_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String doctorIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_doctor.MEDICINE_RECORDS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String medicineRecords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_doctor.DOCTOR_INTRODUCE
     *
     * @return the value of tb_culpro_doctor.DOCTOR_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getDoctorIntroduce() {
        return doctorIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_doctor.DOCTOR_INTRODUCE
     *
     * @param doctorIntroduce the value for tb_culpro_doctor.DOCTOR_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setDoctorIntroduce(String doctorIntroduce) {
        this.doctorIntroduce = doctorIntroduce == null ? null : doctorIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_doctor.MEDICINE_RECORDS
     *
     * @return the value of tb_culpro_doctor.MEDICINE_RECORDS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getMedicineRecords() {
        return medicineRecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_doctor.MEDICINE_RECORDS
     *
     * @param medicineRecords the value for tb_culpro_doctor.MEDICINE_RECORDS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setMedicineRecords(String medicineRecords) {
        this.medicineRecords = medicineRecords == null ? null : medicineRecords.trim();
    }
}