package com.zyyglxt.dataobject;

import java.util.Date;

public class FamProDO extends FamProDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.SOURCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.AUTHOR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.VISIT_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Integer visitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_fam_pro.CONTENT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.NAME
     *
     * @return the value of tb_culpro_fam_pro.NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.NAME
     *
     * @param name the value for tb_culpro_fam_pro.NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.SOURCE
     *
     * @return the value of tb_culpro_fam_pro.SOURCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.SOURCE
     *
     * @param source the value for tb_culpro_fam_pro.SOURCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.AUTHOR
     *
     * @return the value of tb_culpro_fam_pro.AUTHOR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.AUTHOR
     *
     * @param author the value for tb_culpro_fam_pro.AUTHOR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.VISIT_NUM
     *
     * @return the value of tb_culpro_fam_pro.VISIT_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Integer getVisitNum() {
        return visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.VISIT_NUM
     *
     * @param visitNum the value for tb_culpro_fam_pro.VISIT_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setVisitNum(Integer visitNum) {
        this.visitNum = visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.STATUS
     *
     * @return the value of tb_culpro_fam_pro.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.STATUS
     *
     * @param status the value for tb_culpro_fam_pro.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.CREATER
     *
     * @return the value of tb_culpro_fam_pro.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.CREATER
     *
     * @param creater the value for tb_culpro_fam_pro.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.itemCreateAt
     *
     * @return the value of tb_culpro_fam_pro.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.itemCreateAt
     *
     * @param itemcreateat the value for tb_culpro_fam_pro.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.UPDATER
     *
     * @return the value of tb_culpro_fam_pro.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.UPDATER
     *
     * @param updater the value for tb_culpro_fam_pro.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.itemUpdateAt
     *
     * @return the value of tb_culpro_fam_pro.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.itemUpdateAt
     *
     * @param itemupdateat the value for tb_culpro_fam_pro.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_fam_pro.CONTENT
     *
     * @return the value of tb_culpro_fam_pro.CONTENT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_fam_pro.CONTENT
     *
     * @param content the value for tb_culpro_fam_pro.CONTENT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}