package com.zyyglxt.dataobject;

import java.util.Date;

public class FileDO extends FileDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_file.DATA_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String dataCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_file.UPLOADER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_file.UPLOADER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String uploaderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_file.FILE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_file.FILE_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_file.FILE_SIZE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Double fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_file.FILE_PATH
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_file.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_file.DATA_CODE
     *
     * @return the value of tb_culpro_file.DATA_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getDataCode() {
        return dataCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_file.DATA_CODE
     *
     * @param dataCode the value for tb_culpro_file.DATA_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setDataCode(String dataCode) {
        this.dataCode = dataCode == null ? null : dataCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_file.UPLOADER
     *
     * @return the value of tb_culpro_file.UPLOADER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_file.UPLOADER
     *
     * @param uploader the value for tb_culpro_file.UPLOADER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUploader(String uploader) {
        this.uploader = uploader == null ? null : uploader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_file.UPLOADER_CODE
     *
     * @return the value of tb_culpro_file.UPLOADER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUploaderCode() {
        return uploaderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_file.UPLOADER_CODE
     *
     * @param uploaderCode the value for tb_culpro_file.UPLOADER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUploaderCode(String uploaderCode) {
        this.uploaderCode = uploaderCode == null ? null : uploaderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_file.FILE_NAME
     *
     * @return the value of tb_culpro_file.FILE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_file.FILE_NAME
     *
     * @param fileName the value for tb_culpro_file.FILE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_file.FILE_TYPE
     *
     * @return the value of tb_culpro_file.FILE_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_file.FILE_TYPE
     *
     * @param fileType the value for tb_culpro_file.FILE_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_file.FILE_SIZE
     *
     * @return the value of tb_culpro_file.FILE_SIZE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Double getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_file.FILE_SIZE
     *
     * @param fileSize the value for tb_culpro_file.FILE_SIZE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_file.FILE_PATH
     *
     * @return the value of tb_culpro_file.FILE_PATH
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_file.FILE_PATH
     *
     * @param filePath the value for tb_culpro_file.FILE_PATH
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_file.itemCreateAt
     *
     * @return the value of tb_culpro_file.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_file.itemCreateAt
     *
     * @param itemcreateat the value for tb_culpro_file.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }
}