package com.zyyglxt.dataobject;

import java.util.Date;

public class HealthCareChineseMedicineDO extends HealthCareChineseMedicineDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_ALIAS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_SOURCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_HARVESTING
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineHarvesting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_TASTE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineTaste;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_MER_TRO
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineMerTro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_EFFECT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineEffect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_USAGE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineUsage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String chineseMedicineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_health_care_chinese_medicine.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_NAME
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineName() {
        return chineseMedicineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_NAME
     *
     * @param chineseMedicineName the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineName(String chineseMedicineName) {
        this.chineseMedicineName = chineseMedicineName == null ? null : chineseMedicineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_TYPE
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineType() {
        return chineseMedicineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_TYPE
     *
     * @param chineseMedicineType the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineType(String chineseMedicineType) {
        this.chineseMedicineType = chineseMedicineType == null ? null : chineseMedicineType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_ALIAS
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_ALIAS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineAlias() {
        return chineseMedicineAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_ALIAS
     *
     * @param chineseMedicineAlias the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_ALIAS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineAlias(String chineseMedicineAlias) {
        this.chineseMedicineAlias = chineseMedicineAlias == null ? null : chineseMedicineAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_SOURCE
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_SOURCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineSource() {
        return chineseMedicineSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_SOURCE
     *
     * @param chineseMedicineSource the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_SOURCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineSource(String chineseMedicineSource) {
        this.chineseMedicineSource = chineseMedicineSource == null ? null : chineseMedicineSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_HARVESTING
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_HARVESTING
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineHarvesting() {
        return chineseMedicineHarvesting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_HARVESTING
     *
     * @param chineseMedicineHarvesting the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_HARVESTING
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineHarvesting(String chineseMedicineHarvesting) {
        this.chineseMedicineHarvesting = chineseMedicineHarvesting == null ? null : chineseMedicineHarvesting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_TASTE
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_TASTE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineTaste() {
        return chineseMedicineTaste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_TASTE
     *
     * @param chineseMedicineTaste the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_TASTE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineTaste(String chineseMedicineTaste) {
        this.chineseMedicineTaste = chineseMedicineTaste == null ? null : chineseMedicineTaste.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_MER_TRO
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_MER_TRO
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineMerTro() {
        return chineseMedicineMerTro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_MER_TRO
     *
     * @param chineseMedicineMerTro the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_MER_TRO
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineMerTro(String chineseMedicineMerTro) {
        this.chineseMedicineMerTro = chineseMedicineMerTro == null ? null : chineseMedicineMerTro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_EFFECT
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_EFFECT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineEffect() {
        return chineseMedicineEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_EFFECT
     *
     * @param chineseMedicineEffect the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_EFFECT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineEffect(String chineseMedicineEffect) {
        this.chineseMedicineEffect = chineseMedicineEffect == null ? null : chineseMedicineEffect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_USAGE
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_USAGE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineUsage() {
        return chineseMedicineUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_USAGE
     *
     * @param chineseMedicineUsage the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_USAGE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineUsage(String chineseMedicineUsage) {
        this.chineseMedicineUsage = chineseMedicineUsage == null ? null : chineseMedicineUsage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_STATUS
     *
     * @return the value of tb_health_care_chinese_medicine.CHINESE_MEDICINE_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getChineseMedicineStatus() {
        return chineseMedicineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CHINESE_MEDICINE_STATUS
     *
     * @param chineseMedicineStatus the value for tb_health_care_chinese_medicine.CHINESE_MEDICINE_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setChineseMedicineStatus(String chineseMedicineStatus) {
        this.chineseMedicineStatus = chineseMedicineStatus == null ? null : chineseMedicineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.CREATER
     *
     * @return the value of tb_health_care_chinese_medicine.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.CREATER
     *
     * @param creater the value for tb_health_care_chinese_medicine.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.itemCreateAt
     *
     * @return the value of tb_health_care_chinese_medicine.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.itemCreateAt
     *
     * @param itemcreateat the value for tb_health_care_chinese_medicine.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.UPDATER
     *
     * @return the value of tb_health_care_chinese_medicine.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.UPDATER
     *
     * @param updater the value for tb_health_care_chinese_medicine.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_health_care_chinese_medicine.itemUpdateAt
     *
     * @return the value of tb_health_care_chinese_medicine.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_health_care_chinese_medicine.itemUpdateAt
     *
     * @param itemupdateat the value for tb_health_care_chinese_medicine.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}