package com.zyyglxt.dataobject;

import java.util.Date;

public class HospDO extends HospDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_LEVEL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_TELEPHONE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_ADDRESS_PRO
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalAddressPro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_ADDRESS_CITY
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalAddressCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_ADDRESS_COUNTRY
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalAddressCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_ADDRESS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_LINK
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_hosp.HOSPITAL_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String hospitalIntroduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_NAME
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_NAME
     *
     * @param hospitalName the value for tb_culpro_hosp.HOSPITAL_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_LEVEL
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_LEVEL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalLevel() {
        return hospitalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_LEVEL
     *
     * @param hospitalLevel the value for tb_culpro_hosp.HOSPITAL_LEVEL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalLevel(String hospitalLevel) {
        this.hospitalLevel = hospitalLevel == null ? null : hospitalLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_TELEPHONE
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_TELEPHONE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalTelephone() {
        return hospitalTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_TELEPHONE
     *
     * @param hospitalTelephone the value for tb_culpro_hosp.HOSPITAL_TELEPHONE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalTelephone(String hospitalTelephone) {
        this.hospitalTelephone = hospitalTelephone == null ? null : hospitalTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_ADDRESS_PRO
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_ADDRESS_PRO
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalAddressPro() {
        return hospitalAddressPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_ADDRESS_PRO
     *
     * @param hospitalAddressPro the value for tb_culpro_hosp.HOSPITAL_ADDRESS_PRO
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalAddressPro(String hospitalAddressPro) {
        this.hospitalAddressPro = hospitalAddressPro == null ? null : hospitalAddressPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_ADDRESS_CITY
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_ADDRESS_CITY
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalAddressCity() {
        return hospitalAddressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_ADDRESS_CITY
     *
     * @param hospitalAddressCity the value for tb_culpro_hosp.HOSPITAL_ADDRESS_CITY
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalAddressCity(String hospitalAddressCity) {
        this.hospitalAddressCity = hospitalAddressCity == null ? null : hospitalAddressCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_ADDRESS_COUNTRY
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_ADDRESS_COUNTRY
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalAddressCountry() {
        return hospitalAddressCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_ADDRESS_COUNTRY
     *
     * @param hospitalAddressCountry the value for tb_culpro_hosp.HOSPITAL_ADDRESS_COUNTRY
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalAddressCountry(String hospitalAddressCountry) {
        this.hospitalAddressCountry = hospitalAddressCountry == null ? null : hospitalAddressCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_ADDRESS
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_ADDRESS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalAddress() {
        return hospitalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_ADDRESS
     *
     * @param hospitalAddress the value for tb_culpro_hosp.HOSPITAL_ADDRESS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalAddress(String hospitalAddress) {
        this.hospitalAddress = hospitalAddress == null ? null : hospitalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_LINK
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_LINK
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalLink() {
        return hospitalLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_LINK
     *
     * @param hospitalLink the value for tb_culpro_hosp.HOSPITAL_LINK
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalLink(String hospitalLink) {
        this.hospitalLink = hospitalLink == null ? null : hospitalLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_STATUS
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalStatus() {
        return hospitalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_STATUS
     *
     * @param hospitalStatus the value for tb_culpro_hosp.HOSPITAL_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalStatus(String hospitalStatus) {
        this.hospitalStatus = hospitalStatus == null ? null : hospitalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.CREATER
     *
     * @return the value of tb_culpro_hosp.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.CREATER
     *
     * @param creater the value for tb_culpro_hosp.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.itemCreateAt
     *
     * @return the value of tb_culpro_hosp.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.itemCreateAt
     *
     * @param itemcreateat the value for tb_culpro_hosp.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.UPDATER
     *
     * @return the value of tb_culpro_hosp.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.UPDATER
     *
     * @param updater the value for tb_culpro_hosp.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.itemUpdateAt
     *
     * @return the value of tb_culpro_hosp.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.itemUpdateAt
     *
     * @param itemupdateat the value for tb_culpro_hosp.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_hosp.HOSPITAL_INTRODUCE
     *
     * @return the value of tb_culpro_hosp.HOSPITAL_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getHospitalIntroduce() {
        return hospitalIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_hosp.HOSPITAL_INTRODUCE
     *
     * @param hospitalIntroduce the value for tb_culpro_hosp.HOSPITAL_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setHospitalIntroduce(String hospitalIntroduce) {
        this.hospitalIntroduce = hospitalIntroduce == null ? null : hospitalIntroduce.trim();
    }
}