package com.zyyglxt.dataobject;

import java.util.Date;

public class IndustrialDevelopCooExcDO extends IndustrialDevelopCooExcDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String cooperationExchangeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_LEADER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String cooperationExchangeLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.VISIT_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Integer visitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.PROJECT_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String projectIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.PROJECT_UNIT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String projectUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.CONTACTS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.PHONE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.COO_ORG
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String cooOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_coo_exc.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_NAME
     *
     * @return the value of tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCooperationExchangeName() {
        return cooperationExchangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_NAME
     *
     * @param cooperationExchangeName the value for tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCooperationExchangeName(String cooperationExchangeName) {
        this.cooperationExchangeName = cooperationExchangeName == null ? null : cooperationExchangeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_LEADER
     *
     * @return the value of tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_LEADER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCooperationExchangeLeader() {
        return cooperationExchangeLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_LEADER
     *
     * @param cooperationExchangeLeader the value for tb_industrial_develop_coo_exc.COOPERATION_EXCHANGE_LEADER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCooperationExchangeLeader(String cooperationExchangeLeader) {
        this.cooperationExchangeLeader = cooperationExchangeLeader == null ? null : cooperationExchangeLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.VISIT_NUM
     *
     * @return the value of tb_industrial_develop_coo_exc.VISIT_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Integer getVisitNum() {
        return visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.VISIT_NUM
     *
     * @param visitNum the value for tb_industrial_develop_coo_exc.VISIT_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setVisitNum(Integer visitNum) {
        this.visitNum = visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.PROJECT_INTRODUCE
     *
     * @return the value of tb_industrial_develop_coo_exc.PROJECT_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getProjectIntroduce() {
        return projectIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.PROJECT_INTRODUCE
     *
     * @param projectIntroduce the value for tb_industrial_develop_coo_exc.PROJECT_INTRODUCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setProjectIntroduce(String projectIntroduce) {
        this.projectIntroduce = projectIntroduce == null ? null : projectIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.PROJECT_UNIT
     *
     * @return the value of tb_industrial_develop_coo_exc.PROJECT_UNIT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getProjectUnit() {
        return projectUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.PROJECT_UNIT
     *
     * @param projectUnit the value for tb_industrial_develop_coo_exc.PROJECT_UNIT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setProjectUnit(String projectUnit) {
        this.projectUnit = projectUnit == null ? null : projectUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.CONTACTS
     *
     * @return the value of tb_industrial_develop_coo_exc.CONTACTS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.CONTACTS
     *
     * @param contacts the value for tb_industrial_develop_coo_exc.CONTACTS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.PHONE
     *
     * @return the value of tb_industrial_develop_coo_exc.PHONE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.PHONE
     *
     * @param phone the value for tb_industrial_develop_coo_exc.PHONE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.COO_ORG
     *
     * @return the value of tb_industrial_develop_coo_exc.COO_ORG
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCooOrg() {
        return cooOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.COO_ORG
     *
     * @param cooOrg the value for tb_industrial_develop_coo_exc.COO_ORG
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCooOrg(String cooOrg) {
        this.cooOrg = cooOrg == null ? null : cooOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.STATUS
     *
     * @return the value of tb_industrial_develop_coo_exc.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.STATUS
     *
     * @param status the value for tb_industrial_develop_coo_exc.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.CREATER
     *
     * @return the value of tb_industrial_develop_coo_exc.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.CREATER
     *
     * @param creater the value for tb_industrial_develop_coo_exc.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.itemCreateAt
     *
     * @return the value of tb_industrial_develop_coo_exc.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.itemCreateAt
     *
     * @param itemcreateat the value for tb_industrial_develop_coo_exc.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.UPDATER
     *
     * @return the value of tb_industrial_develop_coo_exc.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.UPDATER
     *
     * @param updater the value for tb_industrial_develop_coo_exc.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_coo_exc.itemUpdateAt
     *
     * @return the value of tb_industrial_develop_coo_exc.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_coo_exc.itemUpdateAt
     *
     * @param itemupdateat the value for tb_industrial_develop_coo_exc.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}