package com.zyyglxt.dataobject;

import java.util.Date;

public class IndustrialDevelopExpertDO extends IndustrialDevelopExpertDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert.USER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert.FILED
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String filed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert.USER_CODE
     *
     * @return the value of tb_industrial_develop_expert.USER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert.USER_CODE
     *
     * @param userCode the value for tb_industrial_develop_expert.USER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert.FILED
     *
     * @return the value of tb_industrial_develop_expert.FILED
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getFiled() {
        return filed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert.FILED
     *
     * @param filed the value for tb_industrial_develop_expert.FILED
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setFiled(String filed) {
        this.filed = filed == null ? null : filed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert.CREATER
     *
     * @return the value of tb_industrial_develop_expert.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert.CREATER
     *
     * @param creater the value for tb_industrial_develop_expert.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert.itemCreateAt
     *
     * @return the value of tb_industrial_develop_expert.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert.itemCreateAt
     *
     * @param itemcreateat the value for tb_industrial_develop_expert.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert.UPDATER
     *
     * @return the value of tb_industrial_develop_expert.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert.UPDATER
     *
     * @param updater the value for tb_industrial_develop_expert.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert.itemUpdateAt
     *
     * @return the value of tb_industrial_develop_expert.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert.itemUpdateAt
     *
     * @param itemupdateat the value for tb_industrial_develop_expert.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}