package com.zyyglxt.dataobject;

import java.util.Date;

public class IndustrialDevelopOffDO extends IndustrialDevelopOffDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_off.YEAR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_off.START_TIME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_off.END_TIME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_off.ISIMP
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String isimp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_off.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_off.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_off.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_off.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_off.YEAR
     *
     * @return the value of tb_industrial_develop_off.YEAR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_off.YEAR
     *
     * @param year the value for tb_industrial_develop_off.YEAR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_off.START_TIME
     *
     * @return the value of tb_industrial_develop_off.START_TIME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_off.START_TIME
     *
     * @param startTime the value for tb_industrial_develop_off.START_TIME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_off.END_TIME
     *
     * @return the value of tb_industrial_develop_off.END_TIME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_off.END_TIME
     *
     * @param endTime the value for tb_industrial_develop_off.END_TIME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_off.ISIMP
     *
     * @return the value of tb_industrial_develop_off.ISIMP
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getIsimp() {
        return isimp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_off.ISIMP
     *
     * @param isimp the value for tb_industrial_develop_off.ISIMP
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setIsimp(String isimp) {
        this.isimp = isimp == null ? null : isimp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_off.CREATER
     *
     * @return the value of tb_industrial_develop_off.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_off.CREATER
     *
     * @param creater the value for tb_industrial_develop_off.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_off.itemCreateAt
     *
     * @return the value of tb_industrial_develop_off.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_off.itemCreateAt
     *
     * @param itemcreateat the value for tb_industrial_develop_off.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_off.UPDATER
     *
     * @return the value of tb_industrial_develop_off.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_off.UPDATER
     *
     * @param updater the value for tb_industrial_develop_off.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_off.itemUpdateAt
     *
     * @return the value of tb_industrial_develop_off.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_off.itemUpdateAt
     *
     * @param itemupdateat the value for tb_industrial_develop_off.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}