package com.zyyglxt.dataobject;

import java.util.Date;

public class IndustrialDevelopSciAchiDO extends IndustrialDevelopSciAchiDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String industrialDevelopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_LEADER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String industrialDevelopLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.VISIT_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Integer visitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_SOURCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String industrialDevelopSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_AUTHOR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String industrialDevelopAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String industrialDevelopStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_NAME
     *
     * @return the value of tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getIndustrialDevelopName() {
        return industrialDevelopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_NAME
     *
     * @param industrialDevelopName the value for tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setIndustrialDevelopName(String industrialDevelopName) {
        this.industrialDevelopName = industrialDevelopName == null ? null : industrialDevelopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_LEADER
     *
     * @return the value of tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_LEADER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getIndustrialDevelopLeader() {
        return industrialDevelopLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_LEADER
     *
     * @param industrialDevelopLeader the value for tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_LEADER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setIndustrialDevelopLeader(String industrialDevelopLeader) {
        this.industrialDevelopLeader = industrialDevelopLeader == null ? null : industrialDevelopLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.VISIT_NUM
     *
     * @return the value of tb_industrial_develop_sci_achi.VISIT_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Integer getVisitNum() {
        return visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.VISIT_NUM
     *
     * @param visitNum the value for tb_industrial_develop_sci_achi.VISIT_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setVisitNum(Integer visitNum) {
        this.visitNum = visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_SOURCE
     *
     * @return the value of tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_SOURCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getIndustrialDevelopSource() {
        return industrialDevelopSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_SOURCE
     *
     * @param industrialDevelopSource the value for tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_SOURCE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setIndustrialDevelopSource(String industrialDevelopSource) {
        this.industrialDevelopSource = industrialDevelopSource == null ? null : industrialDevelopSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_AUTHOR
     *
     * @return the value of tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_AUTHOR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getIndustrialDevelopAuthor() {
        return industrialDevelopAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_AUTHOR
     *
     * @param industrialDevelopAuthor the value for tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_AUTHOR
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setIndustrialDevelopAuthor(String industrialDevelopAuthor) {
        this.industrialDevelopAuthor = industrialDevelopAuthor == null ? null : industrialDevelopAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_STATUS
     *
     * @return the value of tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getIndustrialDevelopStatus() {
        return industrialDevelopStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_STATUS
     *
     * @param industrialDevelopStatus the value for tb_industrial_develop_sci_achi.INDUSTRIAL_DEVELOP_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setIndustrialDevelopStatus(String industrialDevelopStatus) {
        this.industrialDevelopStatus = industrialDevelopStatus == null ? null : industrialDevelopStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.CREATER
     *
     * @return the value of tb_industrial_develop_sci_achi.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.CREATER
     *
     * @param creater the value for tb_industrial_develop_sci_achi.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.itemCreateAt
     *
     * @return the value of tb_industrial_develop_sci_achi.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.itemCreateAt
     *
     * @param itemcreateat the value for tb_industrial_develop_sci_achi.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.UPDATER
     *
     * @return the value of tb_industrial_develop_sci_achi.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.UPDATER
     *
     * @param updater the value for tb_industrial_develop_sci_achi.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_sci_achi.itemUpdateAt
     *
     * @return the value of tb_industrial_develop_sci_achi.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_sci_achi.itemUpdateAt
     *
     * @param itemupdateat the value for tb_industrial_develop_sci_achi.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}