package com.zyyglxt.dataobject;

import java.util.Date;

public class IndustrialDevelopTopicDO extends IndustrialDevelopTopicDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.PROJECT_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.DISCIPLINE_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String disciplineCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.DISCIPLINE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String disciplineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.APPLICANT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String applicant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.COMPANY
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.POSTAL_ADDRESS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String postalAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.POSTAL_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.CONTACT_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String contactCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.EMAIL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.APPLICATION_DATE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date applicationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.EXAMINE_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String examineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.USER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_topic.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.PROJECT_NAME
     *
     * @return the value of tb_industrial_develop_topic.PROJECT_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.PROJECT_NAME
     *
     * @param projectName the value for tb_industrial_develop_topic.PROJECT_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.DISCIPLINE_CODE
     *
     * @return the value of tb_industrial_develop_topic.DISCIPLINE_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getDisciplineCode() {
        return disciplineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.DISCIPLINE_CODE
     *
     * @param disciplineCode the value for tb_industrial_develop_topic.DISCIPLINE_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setDisciplineCode(String disciplineCode) {
        this.disciplineCode = disciplineCode == null ? null : disciplineCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.DISCIPLINE_NAME
     *
     * @return the value of tb_industrial_develop_topic.DISCIPLINE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getDisciplineName() {
        return disciplineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.DISCIPLINE_NAME
     *
     * @param disciplineName the value for tb_industrial_develop_topic.DISCIPLINE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setDisciplineName(String disciplineName) {
        this.disciplineName = disciplineName == null ? null : disciplineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.APPLICANT
     *
     * @return the value of tb_industrial_develop_topic.APPLICANT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.APPLICANT
     *
     * @param applicant the value for tb_industrial_develop_topic.APPLICANT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant == null ? null : applicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.COMPANY
     *
     * @return the value of tb_industrial_develop_topic.COMPANY
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.COMPANY
     *
     * @param company the value for tb_industrial_develop_topic.COMPANY
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.POSTAL_ADDRESS
     *
     * @return the value of tb_industrial_develop_topic.POSTAL_ADDRESS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getPostalAddress() {
        return postalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.POSTAL_ADDRESS
     *
     * @param postalAddress the value for tb_industrial_develop_topic.POSTAL_ADDRESS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setPostalAddress(String postalAddress) {
        this.postalAddress = postalAddress == null ? null : postalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.POSTAL_CODE
     *
     * @return the value of tb_industrial_develop_topic.POSTAL_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.POSTAL_CODE
     *
     * @param postalCode the value for tb_industrial_develop_topic.POSTAL_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.CONTACT_CODE
     *
     * @return the value of tb_industrial_develop_topic.CONTACT_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getContactCode() {
        return contactCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.CONTACT_CODE
     *
     * @param contactCode the value for tb_industrial_develop_topic.CONTACT_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setContactCode(String contactCode) {
        this.contactCode = contactCode == null ? null : contactCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.EMAIL
     *
     * @return the value of tb_industrial_develop_topic.EMAIL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.EMAIL
     *
     * @param email the value for tb_industrial_develop_topic.EMAIL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.APPLICATION_DATE
     *
     * @return the value of tb_industrial_develop_topic.APPLICATION_DATE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getApplicationDate() {
        return applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.APPLICATION_DATE
     *
     * @param applicationDate the value for tb_industrial_develop_topic.APPLICATION_DATE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.STATUS
     *
     * @return the value of tb_industrial_develop_topic.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.STATUS
     *
     * @param status the value for tb_industrial_develop_topic.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.EXAMINE_STATUS
     *
     * @return the value of tb_industrial_develop_topic.EXAMINE_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getExamineStatus() {
        return examineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.EXAMINE_STATUS
     *
     * @param examineStatus the value for tb_industrial_develop_topic.EXAMINE_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setExamineStatus(String examineStatus) {
        this.examineStatus = examineStatus == null ? null : examineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.USER_CODE
     *
     * @return the value of tb_industrial_develop_topic.USER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.USER_CODE
     *
     * @param userCode the value for tb_industrial_develop_topic.USER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.CREATER
     *
     * @return the value of tb_industrial_develop_topic.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.CREATER
     *
     * @param creater the value for tb_industrial_develop_topic.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.itemCreateAt
     *
     * @return the value of tb_industrial_develop_topic.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.itemCreateAt
     *
     * @param itemcreateat the value for tb_industrial_develop_topic.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.UPDATER
     *
     * @return the value of tb_industrial_develop_topic.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.UPDATER
     *
     * @param updater the value for tb_industrial_develop_topic.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_topic.itemUpdateAt
     *
     * @return the value of tb_industrial_develop_topic.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_topic.itemUpdateAt
     *
     * @param itemupdateat the value for tb_industrial_develop_topic.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}