package com.zyyglxt.dataobject;

import java.util.Date;

public class IndustrialDevelopExpertRefDO extends IndustrialDevelopExpertRefDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert_ref.EXPERT_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String expertCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert_ref.TOPIC_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String topicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert_ref.EXMAINE_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String exmaineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert_ref.OPINION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String opinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert_ref.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert_ref.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert_ref.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_expert_ref.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert_ref.EXPERT_CODE
     *
     * @return the value of tb_industrial_develop_expert_ref.EXPERT_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getExpertCode() {
        return expertCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert_ref.EXPERT_CODE
     *
     * @param expertCode the value for tb_industrial_develop_expert_ref.EXPERT_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setExpertCode(String expertCode) {
        this.expertCode = expertCode == null ? null : expertCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert_ref.TOPIC_CODE
     *
     * @return the value of tb_industrial_develop_expert_ref.TOPIC_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getTopicCode() {
        return topicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert_ref.TOPIC_CODE
     *
     * @param topicCode the value for tb_industrial_develop_expert_ref.TOPIC_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setTopicCode(String topicCode) {
        this.topicCode = topicCode == null ? null : topicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert_ref.EXMAINE_STATUS
     *
     * @return the value of tb_industrial_develop_expert_ref.EXMAINE_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getExmaineStatus() {
        return exmaineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert_ref.EXMAINE_STATUS
     *
     * @param exmaineStatus the value for tb_industrial_develop_expert_ref.EXMAINE_STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setExmaineStatus(String exmaineStatus) {
        this.exmaineStatus = exmaineStatus == null ? null : exmaineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert_ref.OPINION
     *
     * @return the value of tb_industrial_develop_expert_ref.OPINION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getOpinion() {
        return opinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert_ref.OPINION
     *
     * @param opinion the value for tb_industrial_develop_expert_ref.OPINION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setOpinion(String opinion) {
        this.opinion = opinion == null ? null : opinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert_ref.CREATER
     *
     * @return the value of tb_industrial_develop_expert_ref.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert_ref.CREATER
     *
     * @param creater the value for tb_industrial_develop_expert_ref.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert_ref.itemCreateAt
     *
     * @return the value of tb_industrial_develop_expert_ref.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert_ref.itemCreateAt
     *
     * @param itemcreateat the value for tb_industrial_develop_expert_ref.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert_ref.UPDATER
     *
     * @return the value of tb_industrial_develop_expert_ref.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert_ref.UPDATER
     *
     * @param updater the value for tb_industrial_develop_expert_ref.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_expert_ref.itemUpdateAt
     *
     * @return the value of tb_industrial_develop_expert_ref.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_expert_ref.itemUpdateAt
     *
     * @param itemupdateat the value for tb_industrial_develop_expert_ref.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}