package com.zyyglxt.dataobject;

import java.util.Date;

public class IndustrialDevelopTalRecDO extends IndustrialDevelopTalRecDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_tal_rec.WORKPLACE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String workplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_tal_rec.POST_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String postNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_tal_rec.CONDITIONS_TREAMENT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String conditionsTreament;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_tal_rec.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_tal_rec.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_tal_rec.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_tal_rec.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_tal_rec.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_tal_rec.WORKPLACE
     *
     * @return the value of tb_industrial_develop_tal_rec.WORKPLACE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getWorkplace() {
        return workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_tal_rec.WORKPLACE
     *
     * @param workplace the value for tb_industrial_develop_tal_rec.WORKPLACE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setWorkplace(String workplace) {
        this.workplace = workplace == null ? null : workplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_tal_rec.POST_NUM
     *
     * @return the value of tb_industrial_develop_tal_rec.POST_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getPostNum() {
        return postNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_tal_rec.POST_NUM
     *
     * @param postNum the value for tb_industrial_develop_tal_rec.POST_NUM
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setPostNum(String postNum) {
        this.postNum = postNum == null ? null : postNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_tal_rec.CONDITIONS_TREAMENT
     *
     * @return the value of tb_industrial_develop_tal_rec.CONDITIONS_TREAMENT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getConditionsTreament() {
        return conditionsTreament;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_tal_rec.CONDITIONS_TREAMENT
     *
     * @param conditionsTreament the value for tb_industrial_develop_tal_rec.CONDITIONS_TREAMENT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setConditionsTreament(String conditionsTreament) {
        this.conditionsTreament = conditionsTreament == null ? null : conditionsTreament.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_tal_rec.STATUS
     *
     * @return the value of tb_industrial_develop_tal_rec.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_tal_rec.STATUS
     *
     * @param status the value for tb_industrial_develop_tal_rec.STATUS
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_tal_rec.CREATER
     *
     * @return the value of tb_industrial_develop_tal_rec.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_tal_rec.CREATER
     *
     * @param creater the value for tb_industrial_develop_tal_rec.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_tal_rec.itemCreateAt
     *
     * @return the value of tb_industrial_develop_tal_rec.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_tal_rec.itemCreateAt
     *
     * @param itemcreateat the value for tb_industrial_develop_tal_rec.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_tal_rec.UPDATER
     *
     * @return the value of tb_industrial_develop_tal_rec.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_tal_rec.UPDATER
     *
     * @param updater the value for tb_industrial_develop_tal_rec.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_industrial_develop_tal_rec.itemUpdateAt
     *
     * @return the value of tb_industrial_develop_tal_rec.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_industrial_develop_tal_rec.itemUpdateAt
     *
     * @param itemupdateat the value for tb_industrial_develop_tal_rec.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}