package com.zyyglxt.dataobject;

import lombok.Data;

@Data
public class IndustrialDevelopSciAchiDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.itemID
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_industrial_develop_sci_achi.itemCode
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String itemcode;

}