package com.zyyglxt.dataobject;

import java.util.Date;

public class LogDO extends LogDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.APP_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.LOG_TITLE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String logTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.LOG_LEVEL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String logLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.APP_CODE
     *
     * @return the value of log.APP_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.APP_CODE
     *
     * @param appCode the value for log.APP_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.LOG_TITLE
     *
     * @return the value of log.LOG_TITLE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getLogTitle() {
        return logTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.LOG_TITLE
     *
     * @param logTitle the value for log.LOG_TITLE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setLogTitle(String logTitle) {
        this.logTitle = logTitle == null ? null : logTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.LOG_LEVEL
     *
     * @return the value of log.LOG_LEVEL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getLogLevel() {
        return logLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.LOG_LEVEL
     *
     * @param logLevel the value for log.LOG_LEVEL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setLogLevel(String logLevel) {
        this.logLevel = logLevel == null ? null : logLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.CREATER
     *
     * @return the value of log.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.CREATER
     *
     * @param creater the value for log.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.itemCreateAt
     *
     * @return the value of log.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.itemCreateAt
     *
     * @param itemcreateat the value for log.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.UPDATER
     *
     * @return the value of log.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.UPDATER
     *
     * @param updater the value for log.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.itemUpdateAt
     *
     * @return the value of log.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.itemUpdateAt
     *
     * @param itemupdateat the value for log.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}