package com.zyyglxt.dataobject;

import java.util.Date;

public class OrganizationDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.itemID
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.itemCode
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private String itemcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.ORG_NAME
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.ORG_CODE
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.ORG_DESCRIPTION
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private String orgDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.ORG_IDENTIFY
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private String orgIdentify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.backup1
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private String backup1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.backup2
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private String backup2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.LEFT
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private Integer left;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.RIGHT
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private Integer right;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.LEVEL
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.CREATER
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.itemCreateAt
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.UPDATER
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.itemUpdateAt
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.itemID
     *
     * @return the value of organization.itemID
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.itemID
     *
     * @param itemid the value for organization.itemID
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.itemCode
     *
     * @return the value of organization.itemCode
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.itemCode
     *
     * @param itemcode the value for organization.itemCode
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode == null ? null : itemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.ORG_NAME
     *
     * @return the value of organization.ORG_NAME
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.ORG_NAME
     *
     * @param orgName the value for organization.ORG_NAME
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.ORG_CODE
     *
     * @return the value of organization.ORG_CODE
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.ORG_CODE
     *
     * @param orgCode the value for organization.ORG_CODE
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.ORG_DESCRIPTION
     *
     * @return the value of organization.ORG_DESCRIPTION
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public String getOrgDescription() {
        return orgDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.ORG_DESCRIPTION
     *
     * @param orgDescription the value for organization.ORG_DESCRIPTION
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setOrgDescription(String orgDescription) {
        this.orgDescription = orgDescription == null ? null : orgDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.ORG_IDENTIFY
     *
     * @return the value of organization.ORG_IDENTIFY
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public String getOrgIdentify() {
        return orgIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.ORG_IDENTIFY
     *
     * @param orgIdentify the value for organization.ORG_IDENTIFY
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setOrgIdentify(String orgIdentify) {
        this.orgIdentify = orgIdentify == null ? null : orgIdentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.backup1
     *
     * @return the value of organization.backup1
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.backup1
     *
     * @param backup1 the value for organization.backup1
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.backup2
     *
     * @return the value of organization.backup2
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.backup2
     *
     * @param backup2 the value for organization.backup2
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.LEFT
     *
     * @return the value of organization.LEFT
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public Integer getLeft() {
        return left;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.LEFT
     *
     * @param left the value for organization.LEFT
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setLeft(Integer left) {
        this.left = left;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.RIGHT
     *
     * @return the value of organization.RIGHT
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public Integer getRight() {
        return right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.RIGHT
     *
     * @param right the value for organization.RIGHT
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setRight(Integer right) {
        this.right = right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.LEVEL
     *
     * @return the value of organization.LEVEL
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.LEVEL
     *
     * @param level the value for organization.LEVEL
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.CREATER
     *
     * @return the value of organization.CREATER
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.CREATER
     *
     * @param creater the value for organization.CREATER
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.itemCreateAt
     *
     * @return the value of organization.itemCreateAt
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.itemCreateAt
     *
     * @param itemcreateat the value for organization.itemCreateAt
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.UPDATER
     *
     * @return the value of organization.UPDATER
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.UPDATER
     *
     * @param updater the value for organization.UPDATER
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.itemUpdateAt
     *
     * @return the value of organization.itemUpdateAt
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.itemUpdateAt
     *
     * @param itemupdateat the value for organization.itemUpdateAt
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}