package com.zyyglxt.dataobject;

import java.util.Date;

public class PreTreDO extends PreTreDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.DATA_TITLE
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private String dataTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.DATA_AUTHOR
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private String dataAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.DATA_SOURCE
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private String dataSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.DATA_STATUS
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private String dataStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.DATA_TYPE
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.VISIT_NUM
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private Integer visitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.CREATER
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.itemCreateAt
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.UPDATER
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.itemUpdateAt
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private Date itemupdateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_culpro_pre_tre.DATA_CONTENT
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    private String dataContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.DATA_TITLE
     *
     * @return the value of tb_culpro_pre_tre.DATA_TITLE
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public String getDataTitle() {
        return dataTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.DATA_TITLE
     *
     * @param dataTitle the value for tb_culpro_pre_tre.DATA_TITLE
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setDataTitle(String dataTitle) {
        this.dataTitle = dataTitle == null ? null : dataTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.DATA_AUTHOR
     *
     * @return the value of tb_culpro_pre_tre.DATA_AUTHOR
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public String getDataAuthor() {
        return dataAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.DATA_AUTHOR
     *
     * @param dataAuthor the value for tb_culpro_pre_tre.DATA_AUTHOR
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setDataAuthor(String dataAuthor) {
        this.dataAuthor = dataAuthor == null ? null : dataAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.DATA_SOURCE
     *
     * @return the value of tb_culpro_pre_tre.DATA_SOURCE
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.DATA_SOURCE
     *
     * @param dataSource the value for tb_culpro_pre_tre.DATA_SOURCE
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.DATA_STATUS
     *
     * @return the value of tb_culpro_pre_tre.DATA_STATUS
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.DATA_STATUS
     *
     * @param dataStatus the value for tb_culpro_pre_tre.DATA_STATUS
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus == null ? null : dataStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.DATA_TYPE
     *
     * @return the value of tb_culpro_pre_tre.DATA_TYPE
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.DATA_TYPE
     *
     * @param dataType the value for tb_culpro_pre_tre.DATA_TYPE
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.VISIT_NUM
     *
     * @return the value of tb_culpro_pre_tre.VISIT_NUM
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public Integer getVisitNum() {
        return visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.VISIT_NUM
     *
     * @param visitNum the value for tb_culpro_pre_tre.VISIT_NUM
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setVisitNum(Integer visitNum) {
        this.visitNum = visitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.CREATER
     *
     * @return the value of tb_culpro_pre_tre.CREATER
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.CREATER
     *
     * @param creater the value for tb_culpro_pre_tre.CREATER
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.itemCreateAt
     *
     * @return the value of tb_culpro_pre_tre.itemCreateAt
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.itemCreateAt
     *
     * @param itemcreateat the value for tb_culpro_pre_tre.itemCreateAt
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.UPDATER
     *
     * @return the value of tb_culpro_pre_tre.UPDATER
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.UPDATER
     *
     * @param updater the value for tb_culpro_pre_tre.UPDATER
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.itemUpdateAt
     *
     * @return the value of tb_culpro_pre_tre.itemUpdateAt
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.itemUpdateAt
     *
     * @param itemupdateat the value for tb_culpro_pre_tre.itemUpdateAt
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_culpro_pre_tre.DATA_CONTENT
     *
     * @return the value of tb_culpro_pre_tre.DATA_CONTENT
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public String getDataContent() {
        return dataContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_culpro_pre_tre.DATA_CONTENT
     *
     * @param dataContent the value for tb_culpro_pre_tre.DATA_CONTENT
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    public void setDataContent(String dataContent) {
        this.dataContent = dataContent == null ? null : dataContent.trim();
    }
}