package com.zyyglxt.dataobject;

import java.util.Date;

public class RoleDO extends RoleDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_DESCRIPTION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String roleDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.APP_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Integer roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_NAME
     *
     * @return the value of role.ROLE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_NAME
     *
     * @param roleName the value for role.ROLE_NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_DESCRIPTION
     *
     * @return the value of role.ROLE_DESCRIPTION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_DESCRIPTION
     *
     * @param roleDescription the value for role.ROLE_DESCRIPTION
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription == null ? null : roleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.APP_CODE
     *
     * @return the value of role.APP_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.APP_CODE
     *
     * @param appCode the value for role.APP_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_TYPE
     *
     * @return the value of role.ROLE_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_TYPE
     *
     * @param roleType the value for role.ROLE_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.CREATER
     *
     * @return the value of role.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.CREATER
     *
     * @param creater the value for role.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.itemCreateAt
     *
     * @return the value of role.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.itemCreateAt
     *
     * @param itemcreateat the value for role.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.UPDATER
     *
     * @return the value of role.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.UPDATER
     *
     * @param updater the value for role.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.itemUpdateAt
     *
     * @return the value of role.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.itemUpdateAt
     *
     * @param itemupdateat the value for role.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}