package com.zyyglxt.dataobject;

import javax.validation.constraints.NotBlank;
import java.util.Date;

public class UserDO extends UserDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ORG_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    @NotBlank(message = "组织机构代码不能为空")
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USERNAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    @NotBlank(message = "用户名不能为空")
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    @NotBlank(message = "密码不能为空")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SALT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.GENDER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IDCARD_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String idcardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IDCARD_NO
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String idcardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.EMAIL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STATE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobilePhone
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    @NotBlank(message = "手机号码不能为空")
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CITYID
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PORTRAIT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private byte[] portrait;

    public UserDO() {

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ORG_CODE
     *
     * @return the value of user.ORG_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ORG_CODE
     *
     * @param orgCode the value for user.ORG_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USERNAME
     *
     * @return the value of user.USERNAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USERNAME
     *
     * @param username the value for user.USERNAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SALT
     *
     * @return the value of user.SALT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SALT
     *
     * @param salt the value for user.SALT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NAME
     *
     * @return the value of user.NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NAME
     *
     * @param name the value for user.NAME
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.GENDER
     *
     * @return the value of user.GENDER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.GENDER
     *
     * @param gender the value for user.GENDER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IDCARD_TYPE
     *
     * @return the value of user.IDCARD_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getIdcardType() {
        return idcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IDCARD_TYPE
     *
     * @param idcardType the value for user.IDCARD_TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setIdcardType(String idcardType) {
        this.idcardType = idcardType == null ? null : idcardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IDCARD_NO
     *
     * @return the value of user.IDCARD_NO
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getIdcardNo() {
        return idcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IDCARD_NO
     *
     * @param idcardNo the value for user.IDCARD_NO
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setIdcardNo(String idcardNo) {
        this.idcardNo = idcardNo == null ? null : idcardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.EMAIL
     *
     * @return the value of user.EMAIL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.EMAIL
     *
     * @param email the value for user.EMAIL
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STATE
     *
     * @return the value of user.STATE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STATE
     *
     * @param state the value for user.STATE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobilePhone
     *
     * @return the value of user.mobilePhone
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobilePhone
     *
     * @param mobilephone the value for user.mobilePhone
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CREATER
     *
     * @return the value of user.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CREATER
     *
     * @param creater the value for user.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.itemCreateAt
     *
     * @return the value of user.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.itemCreateAt
     *
     * @param itemcreateat the value for user.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UPDATER
     *
     * @return the value of user.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    // 构造方法，用于登录时讲用户名存入Session，那么整个项目都可以取到
    public UserDO(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UPDATER
     *
     * @param updater the value for user.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.itemUpdateAt
     *
     * @return the value of user.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.itemUpdateAt
     *
     * @param itemupdateat the value for user.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CITYID
     *
     * @return the value of user.CITYID
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CITYID
     *
     * @param cityid the value for user.CITYID
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TYPE
     *
     * @return the value of user.TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TYPE
     *
     * @param type the value for user.TYPE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PORTRAIT
     *
     * @return the value of user.PORTRAIT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public byte[] getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PORTRAIT
     *
     * @param portrait the value for user.PORTRAIT
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setPortrait(byte[] portrait) {
        this.portrait = portrait;
    }
}
