package com.zyyglxt.dataobject;

import java.util.Date;

public class UserRoleRefDO extends UserRoleRefDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_ref.USER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_ref.APP_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_ref.ROLE_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_ref.PLAT_ROLE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String platRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_ref.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_ref.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemcreateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_ref.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_ref.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    private Date itemupdateat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_ref.USER_CODE
     *
     * @return the value of user_role_ref.USER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_ref.USER_CODE
     *
     * @param userCode the value for user_role_ref.USER_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_ref.APP_CODE
     *
     * @return the value of user_role_ref.APP_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_ref.APP_CODE
     *
     * @param appCode the value for user_role_ref.APP_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_ref.ROLE_CODE
     *
     * @return the value of user_role_ref.ROLE_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_ref.ROLE_CODE
     *
     * @param roleCode the value for user_role_ref.ROLE_CODE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_ref.PLAT_ROLE
     *
     * @return the value of user_role_ref.PLAT_ROLE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getPlatRole() {
        return platRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_ref.PLAT_ROLE
     *
     * @param platRole the value for user_role_ref.PLAT_ROLE
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setPlatRole(String platRole) {
        this.platRole = platRole == null ? null : platRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_ref.CREATER
     *
     * @return the value of user_role_ref.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_ref.CREATER
     *
     * @param creater the value for user_role_ref.CREATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_ref.itemCreateAt
     *
     * @return the value of user_role_ref.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemcreateat() {
        return itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_ref.itemCreateAt
     *
     * @param itemcreateat the value for user_role_ref.itemCreateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemcreateat(Date itemcreateat) {
        this.itemcreateat = itemcreateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_ref.UPDATER
     *
     * @return the value of user_role_ref.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_ref.UPDATER
     *
     * @param updater the value for user_role_ref.UPDATER
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_ref.itemUpdateAt
     *
     * @return the value of user_role_ref.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public Date getItemupdateat() {
        return itemupdateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_ref.itemUpdateAt
     *
     * @param itemupdateat the value for user_role_ref.itemUpdateAt
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    public void setItemupdateat(Date itemupdateat) {
        this.itemupdateat = itemupdateat;
    }
}