package com.zyyglxt.dao;

import com.zyyglxt.dataobject.ChineseCulturalDO;
import com.zyyglxt.dataobject.ChineseCulturalDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChineseCulturalDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_cultural
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    int deleteByPrimaryKey(@Param("key") ChineseCulturalDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_cultural
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    int insert(ChineseCulturalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_cultural
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    int insertSelective(ChineseCulturalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_cultural
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    ChineseCulturalDO selectByPrimaryKey(@Param("key") ChineseCulturalDOKey key , @Param("chineseCulturalType") String chineseCulturalType);

    List<ChineseCulturalDO> selectChineseCulturalList(String chineseCulturalType);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_cultural
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    int updateByPrimaryKeySelective(@Param("key")ChineseCulturalDOKey key ,@Param("chineseCulturalDO") ChineseCulturalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_cultural
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ChineseCulturalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_cultural
     *
     * @mbg.generated Thu Oct 29 16:49:53 CST 2020
     */
    int updateByPrimaryKey(ChineseCulturalDO record);
}