package com.zyyglxt.dao;

import com.zyyglxt.dataobject.ChineseMedicineDO;
import com.zyyglxt.dataobject.ChineseMedicineDOKey;
import com.zyyglxt.dataobject.ChineseMedicineDOWithBLOBs;

import java.util.List;

public interface ChineseMedicineDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(ChineseMedicineDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(ChineseMedicineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(ChineseMedicineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    ChineseMedicineDOWithBLOBs selectByPrimaryKey(ChineseMedicineDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(ChineseMedicineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ChineseMedicineDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(ChineseMedicineDO record);

    List<ChineseMedicineDO> selectAllChineseMedicine();

    List<ChineseMedicineDO> searchChineseMedicine(String keyWord);

    List<ChineseMedicineDO> top5ChineseMedicine();


}