package com.zyyglxt.dao;

import com.zyyglxt.dataobject.DictitemDO;
import com.zyyglxt.dataobject.DictitemDOKey;

public interface DictitemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictitem
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(DictitemDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictitem
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(DictitemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictitem
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(DictitemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictitem
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    DictitemDO selectByPrimaryKey(DictitemDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictitem
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(DictitemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictitem
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(DictitemDO record);
}