package com.zyyglxt.dao;

import com.zyyglxt.dataobject.FileDO;
import com.zyyglxt.dataobject.FileDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FileDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_file
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(FileDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_file
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(FileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_file
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(FileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_file
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    FileDO selectByPrimaryKey(FileDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_file
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(FileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_file
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(FileDO record);

    List<FileDO> selectAllFile();

    List<FileDO> searchFile(String keyWord);

    List<FileDO> top5File();

    FileDO selectFileByDataCode(String dataCode);

    FileDO selectFileByDataCodeAndType(@Param("dataCode") String dataCode, @Param("fileType") String fileType);

    FileDO selectFileByDataCodeAndName(@Param("dataCode") String dataCode, @Param("fileName") String fileName);

    int deleteByDataCode(String dataCode);

    int deleteByDataCodeAndType(@Param("dataCode") String dataCode, @Param("fileType") String fileType);
}