package com.zyyglxt.dao;

import com.zyyglxt.dataobject.HealthCareChineseMedicineDO;
import com.zyyglxt.dataobject.HealthCareChineseMedicineDOKey;

public interface HealthCareChineseMedicineDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(HealthCareChineseMedicineDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(HealthCareChineseMedicineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(HealthCareChineseMedicineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    HealthCareChineseMedicineDO selectByPrimaryKey(HealthCareChineseMedicineDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(HealthCareChineseMedicineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_chinese_medicine
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(HealthCareChineseMedicineDO record);
}