package com.zyyglxt.dao;

import com.zyyglxt.dataobject.HealthCareFamPreDOKey;
import com.zyyglxt.dataobject.HealthSciKnowDO;
import com.zyyglxt.dataobject.HealthSciKnowDOKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface HealthSciKnowDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_sci_know
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(@Param("key") HealthSciKnowDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_sci_know
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(HealthSciKnowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_sci_know
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(HealthSciKnowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_sci_know
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    HealthSciKnowDO selectByPrimaryKey(HealthSciKnowDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_sci_know
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(HealthSciKnowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_sci_know
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(HealthSciKnowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_sci_know
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(HealthSciKnowDO record);
    List<HealthSciKnowDO> selectAllHealthSciKnow();//查询所有科普知识所有数据
    int updateVisitNumHealthSciKnow(HealthSciKnowDOKey key);
}