package com.zyyglxt.dao;

import com.zyyglxt.dataobject.HealthCareFamPreDO;
import com.zyyglxt.dataobject.HealthCareFamPreDOKey;

public interface HealthCareFamPreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_fam_pre
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(HealthCareFamPreDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_fam_pre
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(HealthCareFamPreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_fam_pre
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(HealthCareFamPreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_fam_pre
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    HealthCareFamPreDO selectByPrimaryKey(HealthCareFamPreDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_fam_pre
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(HealthCareFamPreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_fam_pre
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(HealthCareFamPreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_health_care_fam_pre
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(HealthCareFamPreDO record);
}