package com.zyyglxt.dao;

import com.zyyglxt.dataobject.HealthSciKnowDOKey;
import com.zyyglxt.dataobject.IndustrialDevelopCooExcDO;
import com.zyyglxt.dataobject.IndustrialDevelopCooExcDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IndustrialDevelopCooExcDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_coo_exc
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(IndustrialDevelopCooExcDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_coo_exc
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(IndustrialDevelopCooExcDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_coo_exc
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(IndustrialDevelopCooExcDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_coo_exc
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    IndustrialDevelopCooExcDO selectByPrimaryKey(IndustrialDevelopCooExcDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_coo_exc
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(IndustrialDevelopCooExcDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_coo_exc
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(IndustrialDevelopCooExcDO record);

    int updateVisitNumByItemidAndItemcode(IndustrialDevelopCooExcDOKey key);

    List<IndustrialDevelopCooExcDO> selectByPage(@Param("start") int start,@Param("end") int end);

    List<IndustrialDevelopCooExcDO> selectAll(@Param("status") String status);

    int changeStatusToCooExc(@Param("key") IndustrialDevelopCooExcDOKey key, @Param("status") String status);//合作交流数据状态

}