package com.zyyglxt.dao;

import com.zyyglxt.dataobject.IndustrialDevelopTopicDO;
import com.zyyglxt.dataobject.IndustrialDevelopTopicDOKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IndustrialDevelopTopicDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_topic
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(IndustrialDevelopTopicDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_topic
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(IndustrialDevelopTopicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_topic
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(IndustrialDevelopTopicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_topic
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    List<IndustrialDevelopTopicDO> selectByPrimaryKey(@Param("userCode") String userCode);

    IndustrialDevelopTopicDO selectByItemCode(@Param("itemcode") String itemCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_topic
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(IndustrialDevelopTopicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_industrial_develop_topic
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(IndustrialDevelopTopicDO record);

    List<IndustrialDevelopTopicDO> selectByPage(int start, int end);

    List<IndustrialDevelopTopicDO> selectAll();

    //更改项目状态
    int changeStatus(@Param("key") IndustrialDevelopTopicDOKey key, @Param("dataStatus") String status);

    //更改审核状态
    int changeExamineStatus(@Param("key") IndustrialDevelopTopicDOKey key, @Param("dataStatus") String examineStatus);

    List<IndustrialDevelopTopicDO> selectByUserCode(@Param("userCode") String userCode);

    List<IndustrialDevelopTopicDO> selectByCompany(@Param("company") String company);
}
