package com.zyyglxt.dao;

import com.zyyglxt.dataobject.OrganizationDO;

public interface OrganizationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    int insert(OrganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    int insertSelective(OrganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    OrganizationDO selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    int updateByPrimaryKeySelective(OrganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Mon Nov 02 17:38:00 CST 2020
     */
    int updateByPrimaryKey(OrganizationDO record);
}