package com.zyyglxt.dao;

import com.zyyglxt.dataobject.PreTreDO;
import com.zyyglxt.dataobject.PreTreDOKey;

public interface PreTreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_pre_tre
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    int deleteByPrimaryKey(PreTreDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_pre_tre
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    int insert(PreTreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_pre_tre
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    int insertSelective(PreTreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_pre_tre
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    PreTreDO selectByPrimaryKey(PreTreDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_pre_tre
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    int updateByPrimaryKeySelective(PreTreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_pre_tre
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(PreTreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_culpro_pre_tre
     *
     * @mbg.generated Fri Oct 30 16:11:19 CST 2020
     */
    int updateByPrimaryKey(PreTreDO record);
}