package com.zyyglxt.dao;

import com.zyyglxt.dataobject.ResourcesRoleRefDO;
import com.zyyglxt.dataobject.ResourcesRoleRefDOKey;
import org.springframework.stereotype.Repository;

@Repository
public interface ResourcesRoleRefDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(ResourcesRoleRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(ResourcesRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(ResourcesRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    ResourcesRoleRefDO selectByPrimaryKey(ResourcesRoleRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(ResourcesRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(ResourcesRoleRefDO record);

    /**
     * 查询角色权限关系
     * @param itemcode
     * @return
     */
    ResourcesRoleRefDO selectByResCode(String itemcode);
}