package com.zyyglxt.dao;

import com.zyyglxt.dataobject.UserRoleRefDO;
import com.zyyglxt.dataobject.UserRoleRefDOKey;
import org.springframework.stereotype.Repository;

@Repository
public interface UserRoleRefDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int deleteByPrimaryKey(UserRoleRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insert(UserRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int insertSelective(UserRoleRefDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    UserRoleRefDO selectByPrimaryKey(UserRoleRefDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKeySelective(UserRoleRefDO record);
    int updateByKeySelective(UserRoleRefDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_ref
     *
     * @mbg.generated Wed Oct 28 16:25:52 CST 2020
     */
    int updateByPrimaryKey(UserRoleRefDO record);

    /**
     * 根据user_code查询
     * @param itemcode
     * @return
     */
    UserRoleRefDO selectByUserCode(String itemcode);
}